"""empty message

Revision ID: 542ca78ac973
Revises: 6485d00adb92
Create Date: 2024-05-18 15:10:47.317908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '542ca78ac973'
down_revision: Union[str, None] = '6485d00adb92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_code', sa.String(), nullable=False))
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'language_code')
    # ### end Alembic commands ###
